### ISSUE TITLE
Can you add an option in CLI to convert SCHEDULED tags to DEADLINE ?

### ISSUE THREAD

**Issue by justinjk007** [rjhorniii/ical2org-go#1]
The project is awesome by the way.

**Comment by rjhorniii** [comment]
It does make sense to control SCHEDULED vs DEADLINE vs nothing.  I reread the Org Manual and it suggests that any of these make sense depending on your personal workflow methods.  So I'll do that.  But, it does feel odd to have a DEADLINE with both a start and a stop.  Does org really handle that properly?

I'll leave the active date on the headline in all three cases.  It's easy enough for people to remove it after conversion if it's annoying.  Mostly it affects what shows up in the agenda.

Thanks.

**Comment by justinjk007** [comment]
I'm not even sure if `org-mode` supports start and end dates. I have never used that feature actually.

**Comment by rjhorniii** [comment]
Added flags to control both the schedule line and whether headline is active.  Schedule and deadline seem to be OK even if the timestamp does have a range.

This version is pretty stable and functional so it's tagged v0.5
