### ISSUE TITLE
What is the use of ical2org-go/test-all-call.go?

### ISSUE THREAD

**Issue by jpfairbanks** [rjhorniii/ical2org-go#8]
Hi @rjhorniii, this is an awesome tool!

I was looking at the file `ical2org-go/test-all-call.go` and saw that there are two mains in the same program. Also the import in this file is to the un-forked repo of `ics-golang` is this test script out of date?

There is also a the following data file which appears to be missing from the repo `data/xx03614.ics`.

```go
	// get the input chan
	inputChan := parser.GetInputChan()

	//  send a local ics file
	inputChan <- "data/xx03614.ics"

	//  wait for the calendar to be parsed
	parser.Wait()
```

Is this file deprecated? Was it for local testing?

**Comment by rjhorniii** [comment]
It's the start of a test suite.  

I copied it from the original https://github.com/PuloV/ics-golang and have not yet turned it into a test suite for ical2org.

**Comment by rjhorniii** [comment]
Oh, the data/ files are for the test suite too.  That particular one has not yet been anonymized.

**Comment by jpfairbanks** [comment]
yeah that makes sense, I patched it so that it `go build` works and put that in a fork. I can make a PR if you would like.

**Comment by rjhorniii** [comment]
Thanks.  This is my first go project.  I'm gradually getting the hang of packaging for go.
